#!/bin/perl

@errs = ();

while ( <> ) {
#print;
    if ( m@^\s*#define\s+E(\w+)\s+([0-9]+)(\s+/\*\s*(.*)\s*(\*/))?@ ) {
	 $name = $1;
	 $err = $2;
	 $comment = $4;
	 $comment =~ s/\s+$//g;
	 $errs[$err] = $comment;
     }
}

print "/* DO NOT MODIFY! Generated by $0 ", join(" ", @ARGV), " */\n";
print "#ifndef sun\n";
print "#ifndef NeXT\n";
print "const char *sys_errlist[] = {\n";
foreach $err ( 0 .. $#errs ) {
    if ( ! $errs[$err] ) {
	$errs[$err] = "Error $err";
    }
    print '"', $errs[$err], '", ', "\n";
}
print "  0\n};\n";
print "int sys_nerr = ", $#errs + 1, ";\n";
print "#endif\n";
print "#endif\n";

1;
