#!/usr/bin/env perl
# $Id: defs.pl,v 1.6 2007/12/20 12:02:25 stephens Exp $

$args = join(" ", $0, @ARGV);

%defs = ();
%def_files = ();

$source_lines = 0;
if ( $ARGV[0] =~ /^--?s/ ) {
    $source_lines ++;
    shift;
}

$n = shift;
$def = shift;

#print STDERR "n = '$n', def = '$def'\n";

print "/* DO NOT MODIFY!  Generated by defs.pl */\n";
$file = '';
$line = 1;

LINE:
while ( <> ) {
    #print STDERR "$_";
    #print STDERR $_ if ( /$n/ );
    chomp;

    $line ++;

    if ( s/^#(line)?\s*([0-9]+)(\s*"([^"]*)")?// ) {
	 $file = $4 if ( $4 );
	 $line = $2;
    } else {
	 $line ++;
    }

    while ( $_ ne '' ) {
	if ( s/^$n\s*[(]//o ) {
	    $x = '';
	    my $in_paren = 1;
	    while ( $in_paren ) {
	      if ( $_ eq '' ) {
		$_ = <>;
		last LINE if ( ! defined $_ );
		chomp;
		++ $line;
		print STDERR "more paren: $file:$line\n";
	      }
	      s/^([^()"]+|[()"])//;
	      my $app = $1;
	      #print STDERR "app='$app'\n";
	      if ( $app eq '"' ) {
		my $in_quote = 1;
		while ( $in_quote ) {
		  if ( $_ eq '' ) {
		    $_ = <>;
		    last LINE if ( ! defined $_ );
		    ++ $line;
		    #print STDERR "more string: $file:$line\n";
		  }
		  s/^(.|\n)//s;
		  my $c = $1;
		  $in_quote -- if ( $c eq '"' && $app !~ /\\$/s );
		  $in_quote = 0 if ( $c eq '' );
		  $app .= $c;
		}
	      } else {
		$app =~ s/\s+//g;
	      }
	      #print STDERR "$file: x = '$x', app = '$app'\n";
	      $x .= $app;
	      $in_paren ++ if ( $app eq '(' );
	      $in_paren -- if ( $app eq ')' );
	      $in_paren = 0 if ( $app eq '' );
	    }
	    $x =~ s/\)$//;
	    $defs{$x} = 1;
	    $def_files{$x} .= ' ' . $file . ':' . $line;
	    #print STDERR "$file: $x\n";
	} else {
	    s/^\w+|.//;
	    #print STDERR "$_";
	}
    }
}

@defs = sort keys %defs;

#print STDERR join(" ", @defs), "\n";

foreach $x ( @defs ) {
    @xfiles = split(/ /, $def_files{$x});
    $xfiles = '';

    ($file, $line) = split(/:/, $xfiles[1]);
    if ( $source_lines ) {
	print "#line $line \"$file\"\n";

	%xfiles = ();
	foreach $f ( @xfiles ) {
	    ($file, $line) = split(/:/, $f);
	    $xfiles{$file} ++;
	}
	
	$xfiles = join(" ", sort(keys(%xfiles)));
	$xfiles = "\t\t/*$xfiles */";
    }

    print "$def($x)";
    print $xfiles if ( $xfiles );
    print "\n";
}
print "#undef $def\n";

1;


