/* DO NOT MODIFY! Generated by config.pl. */

#define HAS_READLINE 1
#define HAS_HISTORY 1
#define ll_ASSERT_ENABLE 0
#define ll_v_WORD 1
#define ll_USE_INLINE_CALL_MACROS 1
#define ll_USE_GC 1
#define ll_USE_GC_BOEHM 1
#define ll_USE_GC_TREADMILL 0
#define ll_USE_LCACHE 1
#define ll_USE_TYPE_METH_ALIST 1
#define ll_LOOKUP_CACHE_STATS 0
#define ll_USE_FILE_LINE 0
#define ll_BC_RUN_DEBUG 0
#define ll_BC_DUMP 0
#define ll_BC_METER 0
#define ll_GLOBAL_VARS 0
#define ll_MULTIPLICITY 0
#define ll_TYPES_STATIC 1
